name: dentist_cleeaning
description: "Dentist Cleaning tools"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  flutter_animate: ^4.3.0

  go_router: ^11.1.3
  shared_preferences: ^2.2.2

  get_it: ^7.6.4
  logger: ^2.0.2+1

  intl: 0.18.1
  date_format: ^2.0.7

  quickalert: ^1.0.2
  cached_network_image: ^3.3.0

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  top_snackbar_flutter: ^3.1.0

  gap: ^3.0.1
  flex_color_scheme: ^7.3.1

  shimmer_pro: ^0.0.6
  easy_localization: ^3.0.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: DrukCyrMedium
      fonts:
        - asset: assets/fonts/DrukCyr-Medium.ttf
          weight: 700

    - family: SourceSansProRegular
      fonts:
        - asset: assets/fonts/source-sans-pro-regular.ttf
          weight: 400